---
- name: Test tower response
  hosts: all
  gather_facts: false
  become: true
  vars:
     fix_mode: false # Set this to true in job template extra vars
     # Keep this commented if you want to use your host/group/inventory variables
     # This will have higher precedence that host/group/inventory variables but less than extra vars
     # required_pass_minlen: 16
  tasks:
    - name: Reading Configuration Settings
      shell: cat /etc/security/pwquality.conf | grep "=" | grep -v "^#";true
      register: pwquality_results

    - debug:
        msg: "{{ pwquality_results.stdout_lines }}"

    - set_fact:
        pwquality_values: "{{ pwquality_values | default({}) | combine( dict([ item.partition('=')[::2]|map('trim') ]) ) }}"
      with_items: "{{ pwquality_results.stdout_lines }}"
      when: item.split('=')|length > 1
      #no_log: true

    - name: Set fact for the dictionary that contains all the variables to be parsed
      set_fact:
        tower_response: '{{ tower_response | default({}) | combine( {"required_pass_minlen":(required_pass_minlen if required_pass_minlen is defined else ""),"inventory_hostname":inventory_hostname,"ansible_host":ansible_host,"pwquality_values":pwquality_values,"needs_fix":((pwquality_values.minlen|int)<(required_pass_minlen|int) and fix_mode|bool) if required_pass_minlen is defined else False} ) }}'
#      no_log: true

    # Print as loop item
    - name: Tower Response
      set_fact:
        dummy: value # Just to make some task without output
      with_items:
        - "{{ tower_response | to_json }}"
        #- tower_response=>{{ tower_response | to_json }}<=




    # # Print as title
    # # v promenne tower_response je vysledek meho jobu.
    # # tohle je zpusob, jak ho zobrazit v titulce a parsovat pak vystup mezi
    # # "tower_response=>" a "<"
    # # to funguje dobre pro jednoho hosta. 
    # # - name: "tower_response=>{{ tower_response | to_json }}<="
    # #   debug:
    # #     msg: "Dummy message"

    # - name: "Pokus output"
    #   debug:
    #     msg: "{{ awx_response }}"


    # # Print as loop item
    # # V pripade vice hostu, by pristup nahore pouzil pouze prvniho hosta v
    # # inventory. Takhle pomoci with_items se to pouzije pro vsechny hosty. 
    # #- name: Tower Response
    # #  set_fact:
    # #    dummy: value # Just to make some task without output
    # #  with_items:
    # #    - tower_response=>{{ tower_response | to_json }}<=
