---
- hosts: localhost
  tasks:
    - name: "Get test results from the web"
      uri:
        url: "{{ integration_results_url }}"
        return_content: true
      register: results

    - name: "Output test results"
      debug:
        msg: "{{ results.content }}"

        # Tady by se mohlo bud predat do souboru, ktery je v nejake ceste
        # kterou sdilim s nginxem.

    - name: "write output to file"
      run_once: yes
      # Chci, aby to bezelo na kontroleru, bez ohledu na to, co je definovano
      # v hosts. Nechci, aby mi to bezelo na ovladanych nodech, ale jen tady.
      # jenze v pripade awx je localhostem nejaky ten kontejner, ve kterem se to
      # spousti. 
      delegate_to: localhost
      file:
        path: "/var/tmp/reports123"
        state: directory

