---
- hosts: all
  vars:
    - subscription_key: 5429016fb58b4c5ca7146a267c677515
    - temp_path: "/tmp/ssl"
  tasks:
    - name: Create a directory if it does not exist
      ansible.builtin.file:
        path: "{{ temp_path }}"
        state: directory
        mode: '0755'
    - name: Download public certificates with custom HTTP headers
      ansible.builtin.get_url:
        url: https://gw-azwe-dev.skoda-api.com/it/apim/v1/ca-certs
        dest: "{{ temp_path }}/allcerts.pom"
        headers:
          Ocp-Apim-Subscription-Key: "{{ subscription_key }}"
    - name: Split certificate bundle into separate files
      ansible.builtin.shell: |
        awk "BEGIN {c=0;} /BEGIN CERT/{c++} { print > \"cert\" c \".pom\"}" < allcerts.pom
        for f in *.pom; do
          name=`openssl x509 -noout -subject -in $f | awk -F= "{print $NF}" | sed -e "s/^[ \t]*//" | sed "s/[[:space:]]//g"`
          mv -- "$f" "/usr/local/share/ca-certificates/$name.crt"
        done
        update-ca-certificates
      args:
        chdir: "{{ temp_path }}"
    - name: Recursively remove directory
      ansible.builtin.file:
        path: "{{ temp_path }}"
        state: absent